image: registry.hub.docker.com/starefossen/ruby-node:latest
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
stages:
  - publish
  - build-release
  - deploy

before_script:
  - echo Build Number $CI_PIPELINE_IID

expo-publish:
  stage: publish
  only:
    - master
  script:
    - yarn
    - node updateBuildNumber.js $CI_PIPELINE_IID
    - node_modules/expo-cli/bin/expo.js login -u "$EXPO_USERNAME" -p "$EXPO_PASSWORD"
    - node_modules/expo-cli/bin/expo.js publish --release-channel alpha --non-interactive

expo-build-ios:
  stage: build-release
  only:
    - release
  script:
    - yarn
    - node updateBuildNumber.js $CI_PIPELINE_IID
    - node updateVersionNumber.js $CI_PIPELINE_IID
    - node_modules/expo-cli/bin/expo.js login -u "$EXPO_USERNAME" -p "$EXPO_PASSWORD"
    - node_modules/expo-cli/bin/expo.js build:ios --release-channel prod --non-interactive

expo-build-android:
  stage: build-release
  only:
    - release
  script:
    - yarn
    - node updateBuildNumber.js $CI_PIPELINE_IID
    - node updateVersionNumber.js $CI_PIPELINE_IID
    - node_modules/expo-cli/bin/expo.js login -u "$EXPO_USERNAME" -p "$EXPO_PASSWORD"
    - node_modules/expo-cli/bin/expo.js build:android --release-channel prod --non-interactive

fastlane-android:
  stage: deploy
  only:
    - release
  script:
    - yarn
    - node_modules/expo-cli/bin/expo.js login -u "$EXPO_USERNAME" -p "$EXPO_PASSWORD"
    - curl -o app.apk "$(node_modules/expo-cli/bin/expo.js url:apk --non-interactive)"
    - echo "$PLAY_JSON_KEY" > /tmp/play_key.json
    - bundle install
    - bundle exec fastlane supply --track 'beta' --json_key '/tmp/play_key.json' --package_name "com.wordsspeaklouder.uwhelper" --apk "app.apk" --skip_upload_metadata --skip_upload_images --skip_upload_screenshots

fastlane-ios:
  stage: deploy
  only:
    - test
  script:
    - yarn
    - node_modules/expo-cli/bin/expo.js login -u "$EXPO_USERNAME" -p "$EXPO_PASSWORD"
    - curl -o app.ipa "$(node_modules/expo-cli/bin/expo.js url:ipa --non-interactive)"
    - export DELIVER_USERNAME=$APPLE_USER
    - export DELIVER_PASSWORD=$APPLE_PASSWORD
    - bundle install
    - fastlane deliver --verbose --ipa "app.ipa" --skip_screenshots --skip_metadata
