os: osx
osx_image: xcode11
addons:
  homebrew:
    packages:
      - node
      - yarn

cache:
  yarn: true
  directories:
    - node_modules

stages:
  - name: publish
    if: branch = travis-setup
  # - name: build
  #   if: branch = travis-setup
  # - name: deploy
  #   if: branch = travis-setup

jobs:
  include:
    - stage: publish
      script:
        - yarn
        - node updateBuildNumber.js $TRAVIS_BUILD_NUMBER
        - node updateVersionNumber.js $TRAVIS_BUILD_NUMBER
        - node_modules/expo-cli/bin/expo.js login -u $EXPO_USERNAME -p $EXPO_PASSWORD
        - node_modules/expo-cli/bin/expo.js publish --release-channel alpha --non-interactive
