os: osx
osx_image: xcode10.2
addons:
  homebrew:
    packages:
      - node

# stages:
#   - name: publish
#     if: branch = master
#   - name: deploy
#     if: branch = release

jobs:
  include:
    - stage: publish
      script:
        - node updateBuildNumber.js $TRAVIS_BUILD_NUMBER
        - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
        - npx expo publish --release-channel alpha --non-interactive
