os: osx
osx_image: xcode11
addons:
  homebrew:
    packages:
      - node
      - yarn

cache:
  yarn: true
  directories:
    - node_modules

env:
  - ARCH=ios
  - ARCH=android

stages:
  - name: build
    if: branch = travis-setup

jobs:
  include:
    - stage: build
      script:
        - bash scripts/buildAndDeploy.sh
