os: osx
osx_image: xcode11.6

node_js:
  - 12

cache:
  directories:
    - node_modules

stages:
  - name: publish
    if: branch = deploy
  - name: build
    if: branch = deploy

jobs:
  include:
    - stage: publish
      name: "Publish Javascript"
      script:
        - bash scripts/tidy.sh
        - bash scripts/publish.sh
    - stage: build
      name: "Build iOS"
      script:
        - bash scripts/tidy.sh
        - bash scripts/buildApple.sh
    - stage: build
      name: "Build Android"
      script:
        - bash scripts/tidy.sh
        - bash scripts/buildAndroid.sh
