os: osx
osx_image: xcode10.2
addons:
  homebrew:
    packages:
      - node
      - yarn

cache:
  yarn: true
  directories:
    - node_modules

# stages:
#   - name: publish
#     if: branch = master
#   - name: deploy
#     if: branch = release

jobs:
  include:
    - stage: publish
      script:
        - yarn
        - node updateBuildNumber.js $TRAVIS_BUILD_NUMBER
        - node_modules/expo-cli/bin/expo.js login -u $EXPO_USERNAME -p $EXPO_PASSWORD
        - node_modules/expo-cli/bin/expo.js publish --release-channel alpha --non-interactive
