os: osx
osx_image: xcode11
# addons:
#   homebrew:
#     packages:
#       - node
#       - yarn

cache:
  yarn: true
  directories:
    - node_modules

stages:
  - name: build
    if: branch = travis-setup
  # - name: publish
  #   if: branch = travis-setup

jobs:
  - stage: build
    name: 'Build iOS'
    script:
      - bash scripts/buildAndDeploy.sh ios
  # include:
  #   - stage: publish
  #     name: 'Publish Javascript'
  #     script:
  #       - bash scripts/publish.sh
  #
  # - stage: build
  #   name: 'Build Android'
  #   script:
  #     - bash scripts/buildAndDeploy.sh android
